---

name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  validate-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@master

      - name: Extract dependent Pull Requests
        uses: depends-on/depends-on-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pre-commit checks
        run: |
          set -ex
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --with test
          poetry run pre-commit run -a --show-diff-on-failure

  check-all-dependencies-are-merged:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@master

      - name: Check all dependent Pull Requests are merged
        uses: depends-on/depends-on-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check-unmerged-pr: true
...
